### ISSUE TITLE
Filament v3 support

### ISSUE THREAD

**Issue by aymanalhattami** [KoalaFacade/Filament-Navigation-Holder#1]

**Comment by pemudakoding** [comment]
Hi @aymanalhattami with pleasure if you can make this package available for V3

**Comment by aymanalhattami** [comment]
I've made a PR to support filament v3 https://github.com/KoalaFacade/Filament-Navigation-Holder/pull/2

There is another package that supports filament v3 https://github.com/ibrahimBougaoua/filament-menu-scroll-fix

**Comment by pemudakoding** [comment]
> I've made a PR to support filament v3 #2
> 
> There is another package that supports filament v3 https://github.com/ibrahimBougaoua/filament-menu-scroll-fix

Thank you so much it really help us, and im sorry just realise your issue by today
